# Спасибо за загрузку ViaVersion
# Убедитесь, что вы просмотрели все эти опции
# Если вам нужна помощь:
# Дискорд - https://viaversion.com/discord
# viaversion.com - Вкладка обсуждения
# Документация - https://docs.viaversion.com/display/VIAVERSION/Configuration
# Перевод выполнен - Nevil (VK - https://vk.ru/nevil_off1cial или дискорд - Nevil#8588 ) 
# Переводчик - ЯндексПереводчик + доп. авторский перевод некоторых слов/фраз и добавления комментариев к некоторым функциям
#
# true - включить
# false - выключить
#
#----------------------------------------------------------#
#                  ГЛОБАЛЬНЫЕ ПАРАМЕТРЫ                    #
#----------------------------------------------------------#
#
# Следует ли ViaVersion проверять наличие обновлений?
checkforupdates: true
# Отправлять поддерживаемые версии в статус Ping
send-supported-versions: false
# Более простая в настройке альтернатива "block-protocols". Использует читаемые строки версии с возможными префиксами '<' и '>'.
# Примером для блокировки 1.16.4, всего, что ниже 1.16, а также всего, что выше 1.17.1, было бы: ["<1.16", "1.16.4", ">1.17.1"]
# Вы также можете использовать как эту опцию, так и опцию block-protocols одновременно.
block-versions: []
# Блокируйте конкретные номера версий протокола Minecraft.
# Список всех версий протокола Minecraft: http://wiki.vg/Protocol_version_numbers , или используйте генератор: https://via.krusic22.com
block-protocols: []
# Cообщение об отключении
block-disconnect-msg: You are using an unsupported Minecraft version!
# Если вы используете ProtocolLib, мы не сможем перезагрузиться, не кикнув игроков.
# (Мы также не рекомендуем использовать плагин Reload, используйте плагин PluginManager)
# Вы можете настроить сообщение, с которым мы кикаем людей, если вы используете ProtocolLib здесь.
# Сообщение кика при перезагрузке сервера
reload-disconnect-msg: Server reload, please rejoin!
# Мы предупреждаем, когда возникает ошибка преобразования элемента и блокируем данные по версиям, должны ли мы подавлять их? (рекомендуется только в случае рассылки спама)
suppress-conversion-warnings: false
#
#----------------------------------------------------------#
#             ГЛОБАЛЬНЫЙ ОГРАНИЧИТЕЛЬ ПАКЕТОВ              #
#----------------------------------------------------------#
# ЭТА ФУНКЦИЯ ОТКЛЮЧЕНА НА PAPER-СЕРВЕРАХ 1.17.1+, ПОСКОЛЬКУ В НЕЕ ВСТРОЕН ЛУЧШИЙ ОГРАНИЧИТЕЛЬ ПАКЕТОВ
#
# Ограничитель количества пакетов в секунду (PPS) (используйте -1 в max-pss и tracking-period для отключения)
# Клиенты по умолчанию отправляют около 20-90 пакетов в секунду.
#
# Какой максимум в секунду может отправить клиент (используйте %pps для отображения их pps)
# Для отключения функции введите -1
max-pps: 800
# Сообщение при кике за отправку пакетов больше, чем разрешенно. Дописано автором перевода, Nevil
max-pps-kick-msg: You are sending too many packets!
#
# Мы также можем кикнуть их, если за определенный период они определенное количество раз превысят пороговое значение.
#
# Период для отслеживания (в секундах)
# Для отключения функции введите -1
tracking-period: 6
# Сколько пакетов в секунду считается предупреждением
tracking-warning-pps: 120
# Сколько предупреждений за этот интервал мы можем дать
# Это не может быть выше, чем "tracking-period".
tracking-max-warnings: 4
# Сообщение при кике за привышение порога значения пакетов в интервале. Дописано автором перевода, Nevil
tracking-max-kick-msg: You are sending too many packets, :(
#
#----------------------------------------------------------#
#         НАСТРОЙКИ ВАРИАНТОВ НЕСКОЛЬКИХ ВЕРСИЙ            #
#----------------------------------------------------------#
#
# Должны ли мы включить наш патч с голограммой?
# Если они находятся не в том месте, включите это
hologram-patch: false
# Это смещение, должно работать по умолчанию, когда включено.
hologram-y: -0.96
# Должны ли мы отключить анимацию поршня для клиентов 1.11/1.11.1?
# В некоторых случаях при пользовании большим количеством поршней они выходят из строя.
piston-animation-patch: false
# Должны ли мы исправить nbt для клиентов 1.12 и выше, в сообщениях чата (вызывает недопустимый элемент)
chat-nbt-fix: true
# Экспериментально - должны ли мы исправить действие быстрого перемещения shift для клиентов 1.12 (из-за чего shift + двойной щелчок не работают при перемещении элементов) (работает только на серверах на базе 1.8-1.11.2 bukkit)
quick-move-action-fix: false
# Должны ли мы использовать префикс для цвета команды на клиентах 1.13 и выше
team-colour-fix: true
# в 1.13 введено новое автозаполнение, которое может вызвать кик с сервера за спам для серверов старше 1.13, следующая опция полностью отключит его.
disable-1_13-auto-complete: false
# Следующий параметр задержит запрос на завершение таб на количество тиков, если больше 0, если получен другой запрос на завершение таба, предыдущий отменяется
# (PS: при нажатии TAB надо будет ждать некоторое время для его закрытия, как я понял. Дописано автором перевода, Nevil)
1_13-tab-complete-delay: 0
# Для клиентов 1.13 самый маленький (1 слой) снег не имеет столкновения, это отправит их как 2 слоя снега для клиентов 1.13 +, чтобы они не взаимодействовали с ними
fix-low-snow-collision: false
# Зараженные блоки мгновенно разрушаются для клиентов 1.13+, в результате чего они не могут сломать их на дополнительных серверах 1.13. Эта функция переводит их в их обычные каменные варианты
fix-infested-block-breaking: true
# В 1.14 лимит клиентских страниц книг был увеличен до 100 (с 50). Некоторые плагины для защиты от эксплойтов запрещают наличе более 50 страниц. Этот параметр сокращает отредактированные книги до 50 страниц.
truncate-1_14-books: false
# Это предотвращает то, что клиенты, использующие 1.9-1.13 на серверах 1.8, не получают отдачи от урона/не имеют снижения скорости при прохождении под блоком.
change-1_9-hitbox: false
# Аналогично описанному выше, но для игроков 1.14+ на серверах 1.8-1.13.
# ВНИМАНИЕ: Это дает игрокам 1.14+ возможность прокрадываться под блоками, чего игроки под этой версией не могут (прокрадываться в местах высотой всего в 1,5 блока)!
# Еще одна вещь, о которой следует помнить, - это то, что эти игроки могут быть промахнуты снарядами и другими попаданиями, направленными в самую макушку их головы во время пробирания
# (PS, т.е при поподании в голову, например, с лука, урон не пройдёт. Дописано автором перевода, Nevil)
change-1_14-hitbox: false
# Исправлены клиенты 1.14+ на серверах 1.14, имеющие минимальное значение 0 для неполных блоков.
# (PS, исправляет неполный блок света. Дописано автором перевода, Nevil)
fix-non-full-blocklight: true
# Исправлена анимация ходьбы, не показываемая, когда здоровье установлено на значении Float.NaN
# (PS: т.е если не включить, то может быть такое, что у игрока будет 0 хп, тряска экрана, но он будет жив и сможет так-же играть, как обычный игрок. Дописано автором перевода, Nevil)
fix-1_14-health-nan: true
# Должны ли клиенты 1.15+ возрождаться мгновенно/без отображения экрана смерти?
use-1_15-instant-respawn: false
#
# Включить блокировку подключений на стороне сервера для клиентов 1.13+ - все опции в этом разделе (т.е ниже. Дополнил автор перевода) построены вокруг этой опции
serverside-blockconnections: true
# Задает метод для блочных подключений (world для высокоэкспериментального (ИСПОЛЬЗУЙТЕ НА СВОЙ СТРАХ и РИСК) мирового уровня или packet для пакетного уровня)
blockconnection-method: packet
# При активации в хранилище блоков сохраняются только самые важные блоки. (т.е заборы, стеклянные панели и т.д. не будет соединяться с обычными, сплошными блоками)
reduce-blockstorage-memory: false
# При активации соединения к блокам на стороне сервера части цветов с блоками выше будут отправлены в виде стеблей
# Полезно для серверов лобби, где игроки не могут строить, и эти элементы используются декоративно
flowerstem-when-block-above: false
# Виноградные лозы, которые не связаны с блоками, будут сопоставлены с воздухом, иначе в версии 1.13+ все равно смогут подняться по ним.
vine-climb-fix: false
#
# Игнорирует входящие сообщения канала плагина от клиентов 1.16+ с именами каналов длиной более 32 символов.
# У CraftBukkit это ограничение было жестко задано до 1.16, поэтому мы должны предположить, что на любом сервере/прокси-сервере может присутствовать эта произвольная проверка.
ignore-long-1_16-channel-names: true
#
# Заставьте клиента 1.17+ принять пакет ресурсов сервера; они автоматически отключатся, если откажутся.
forced-use-1_17-resource-pack: false
# Сообщение, которое будет отображаться в приглашении, когда клиент 1.17+ получит пакет ресурсов сервера.
resource-pack-1_17-prompt: ''
#
# Кэширование выполняется до тех пор, пока блоки не будут выгружены, чтобы разрешить последующие пакеты обновления блоков, в отличие от мгновенного откэширования при отправке данных первого блока.
# Отключайте это только в том случае, если вы знаете, что делаете.
cache-1_17-light: true
#
# 1.19 форматы типов чатов, используемые для клиентов 1.19.1+.
chat-types-1_19:
  chat.type.text: <%s> %s
  chat.type.announcement: '[%s] %s'
  commands.message.display.incoming: '%s whispers to you: %s'
  chat.type.team.text: '%s <%s> %s'
  chat.type.emote: '* %s %s'
#
#----------------------------------------------------------#
#           НАСТРОЙКИ 1.9+ ВЕРСИИ НА 1.8 СЕРВЕРАХ          #
#----------------------------------------------------------#
#
# Никаких параметров столкновения, они позволяют вам настроить, как работает столкновение.
# Вы хотите, чтобы мы предотвратили столкновение?
prevent-collision: true
# Если вышесказанное верно, должны ли мы автоматически объединять игроков, пока вы этого не сделаете?
auto-team: true
# При включении, если определенные метаданные не могут быть прочитаны, мы не сообщим вам об этом
suppress-metadata-errors: false
# При включении на версии 1.9+ люди смогут блокироваться с помощью щитов
shield-blocking: true
# Если этот параметр активен, основная рука используется вместо выключенной руки, чтобы вызвать блокировку игрока.
# С основной рукой блокировка начинается намного быстрее.
# (Требуется отключить "show-shield-when-sword-in-hand")
no-delay-shield-blocking: false
# Если эта настройка активна, щит будет отображаться немедленно для 1.9+, когда вы держите меч в основной руке.
# Щит исчезает, когда вы переключаетесь на другой предмет.
# (Требуется включить "shield-blocking")
show-shield-when-sword-in-hand: false
# Включите симуляцию тика игрока, это исправит порталы еды, питья и преисподней.
simulate-pt: true
# Должны ли мы использовать nms player для имитации пакетов (может устранить проблемы с античитом)
nms-player-ticking: true
# Должны ли мы исправить панели боссов (те, что с верху, например при спавне взиера. Дополнено автором перевода), чтобы они работали? (По умолчанию: true, отключите, если у вас возникли проблемы)
bossbar-patch: true
# Если ваша панель боссов мигает на 1.9+, установите для этого значение "true". Это сохранит все бары босса на 100% (не рекомендуется)
bossbar-anti-flicker: false
# Это покажет индикатор нового эффекта в правом верхнем углу для игроков играющих на версиях 1.9+
use-new-effect-indicator: true
# Показывать новые сообщения о смерти для 1.9+ на экране смерти
use-new-deathmessages: true
# Если мы будем кэшировать наши элементы, это предотвратит задержку сервера.
item-cache: true
# Исправьте значение anti xray для работы на 1.9+ (если ваш сервер 1.8) Это может привести к увеличению производительности, поэтому отключите его, если вы им не пользуетесь.
anti-xray-patch: true
# Должны ли мы заменить удлиненные поршни, чтобы исправить 1.10.1 (только при частичной нагрузке)
replace-pistons: false
# На какой идентификатор мы должны заменить, по умолчанию используется air. (осторожно, чтобы игроки не застряли, стоя на них)
replacement-piston-id: 0
# Исправляет, что клиенты 1.9+ не отображают удаленные фрагменты и улучшен рендеринг фрагментов при быстром перемещении (увеличивает использование сети и немного снижает частоту кадров клиента)
chunk-border-fix: false
# Принудительное преобразование string -> json
force-json-transform: false
# Сведите к минимуму анимацию перезарядки на серверах 1.8 (т.е сделать быстрее. Дополнено автором перевода, Nevil)
minimize-cooldown: true
# Допускает леворукость 1.9+ (основная рука) на серверах 1.8
left-handed-handling: true
# Измените мировые имена, которые должны быть изменны (название) для каждого ванильного измерения
map-1_16-world-names:
  overworld: minecraft:overworld
  nether: minecraft:the_nether
  end: minecraft:the_end
#
# Перевод выполнен - Nevil (https://vk.ru/nevil_off1cial)
# Переводчик - ЯндексПереводчик + доп. авторский перевод некоторых слов/фраз и добавления комментариев к некоторым функциям